sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kozmotr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kozmotr/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-project"
  env: "Reactproject-env"
  bucket_name: "elasticbeanstalk-us-east-2-789554215820"
  bucket_path: "react-project"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"